config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  resources :blogs
  resources :announcements

      
  
  get 'adminfisher', to: 'admins#index'

  get 'aboutus', to: 'static_pages#aboutus'
  get 'mission', to: 'static_pages#mission'
  get 'company_history', to: 'static_pages#company_history'
  get 'company_structure', to: 'static_pages#company_structure'
  get 'cf_bio', to: 'static_pages#cf_bio'
  get 'rf_bio', to: 'static_pages#rf_bio'
  get 'hysyc_divisions', to: 'static_pages#hhsyc_divisions'
  get 'startchapter', to: 'static_pages#startchapter'
  get 'joinhhsyc', to: 'static_pages#joinhhsyc'
  get 'ccd', to: 'static_pages#ccd'
  get 'red', to: 'static_pages#red'
  
  get 'projects', to: 'static_pages#projects'
  get 'ebobc', to: 'static_pages#ebobc'
  get 'juneteenth', to: 'static_pages#juneteenth'
  get 'mdg', to: 'static_pages#mdg'
  get 'eteam', to: 'static_pages#eteam'

  get 'announcement/show/:id', to: 'announcements#publicshow', as: 'announcements/show'
  get 'publicannindex', to: 'announcements#publicannindex', as: 'announcementlist'
  # get 'index/announcements/:id', to: 'announcements#publicannindex'
  get 'blog/show/:id', to: 'blogs#blogpubshow', as: 'blogs/show'
  get 'publicblogindex', to: 'blogs#publicblogindex', as: 'bloglist'
  
  
  get 'welcome', to: 'welcome#index'
  


  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def aboutus
  end

  def mission
  end

  def company_history
  end

  def company_structure
  end

  def cf_bio
  end

  def rf_bio
  end

  def hhsyc_divisions
  end

  def startchapter
  end

  def joinhhsyc
  end

  def ccd
  end

  def red
  end

  def projects
  end

  def ebobc
  end

  def juneteenth
  end

  def mdg
  end

  def eteam
  end





end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/ccd.html.erb
 <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">HHSYC - Camp Celebrity  Division
                    <!-- <small>founded in 2001</small> -->
                </h1>
                <ol class="breadcrumb">
                    <li><%=link_to 'Home', welcome_path %>
                    </li>  &middot;  
                    <%= link_to "back to About Us", aboutus_path, class: "active" %>
                    </li>  &middot;  
                    <%= link_to "Advisors & Parents (M.A.P)", map_path, class: "active" %>
                    </li>  &middot;  
                    <%= link_to "Camp Celebrity  Division", ccd_path, class: "active" %>
                    </li>  &middot;  
                    <%= link_to "Reality Education Division", red_path, class: "active" %>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <!-- Sidebar Column -->
                <%= render 'shared/sidebar_column' %>
            <!-- Content Column -->
            <div class="col-md-9">
            	<div class="stylestatic">
	             	<!-- <h3>MISSION STATEMENT</h3> -->
	                <p>
	          			Since 1998, Camp Celebrity which is now a division of the Hip-Hop Summit Youth Council offers a free camping experience, along with a host of other services to youths 8-16 years of age.  Our objective is to address the needs of our youth struggling in communities infested with drugs, crime, violence, unemployment and economic decay.  After successfully launching the Camp Cool J Foundation from 1992-97, for Hip-Hop icon LL Cool J, we felt a genuine need to offer Camp Celebrity, especially during the summer months when our youth are not in school.        
	      			</p>
                    <p>
                        In order to save this generation of youth, we must provide them with programs that build character, leadership and self-esteem.  We will accomplish this by conducting an integrated curriculum consisting of education, career development, cultural enrichment, outdoor skills, sports and recreation.
                    </p>
                    <p>
                        At Camp Celebrity, participants will have fun and gain experiences in an environment free of turbulence and the distractions of the inner city.  They will be able to focus their energy towards acquiring the skills needed to address the many issues they are confronted with daily so they can become productive members of our society.
                    </p>
			        </div>	
            </div>
        </div>
        <!-- /.row -->

        <hr>

app/views/static_pages/cf_bio.html.erb
 <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">CHARLES V. K. FISHER
                    <small>HHSYC Chairman & Founder</small>
                </h1>
                <ol class="breadcrumb">
                    <li><%=link_to 'Home', welcome_path %>
                    </li> 
                    <li><%=link_to '<< back', company_structure_path %>
                    <!-- <li class="active">Sidebar Page</li> -->
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <!-- Sidebar Column -->
            
                <div class="col-md-3">
                <div class="list-group">
                    <li class="list-group-item"></li> 
                    <img class="img-circle list-group-item" src="assets/charlesfisher.jpg" alt="Charles Fisher photo" width="200" height="200">
                    <li class="list-group-item"></li>
                    
                </div>
            </div>

            <!-- Content Column -->
            <div class="col-md-9">
                <div class="stylestatic">
                    <!-- <h2>Section Heading</h2> -->
                
                    <p>
                        Charles Fisher was born on November 6, 1954 in Brooklyn New York. He later moved to St.
                        Albans, Queens where he attended Martin Van Buren and Andrew Jackson High Schools as
                        well as York College. His commitment to the community spans over 29 years and includes
                        the creation in 1978 of Youth Enterprise and Associates, a private non-profit organization
                        providing a variety of services to address juvenile delinquency prevention,
                        teen-pregnancy, substance abuse, and literacy awareness. From 1992-1997 he served as
                        the executive director for LL Cool J's Camp Cool J Foundation and during that period he
                        worked as an entertainment consultant to the White House and helped launch President
                        Clinton’s AmeriCorps program.
                    </p>
                    <p>
                        Charles has managed the careers of a host of artists including two-time Grammy award winning recording artist LL Cool J and the Lost Boyz. He also co-discovered and launched the career of two-time Grammy award winning recording artist R. Kelly in 1991 signing him to Jive Records. In 1998 he founded P.O.G. Enterprises, Inc., a multifaceted company that has Food, Management, Marketing, Recording, Film and Publishing divisions. The Film & Music division released the “Game Over” video, which later lead to the ‘Paid in Full” full feature film and the “King of Kings” anti-drug documentary and soundtrack in 2004<!-- (www.KingofKingsDVD.com) -->.
                    </p>
                    <ul>
                        <li>In July of 2001, he founded the National Hip-Hop Summit Youth Council <%= link_to '(www.hhsyc.org)', 'http://www.hhsyc.org/' %>, a non-profit organization founded in Queens and located in New York   City. In its first 5 years
                            the agency has positioned itself to become an effective voice for youth on a host of issues that
                            confront them daily. Their goal is to "change the game" by improving the image and unity
                            within the multi-billion dollar Hip-Hop industry and use its positive influence for the social,
                            political and economic empowerment of our youths and young adults. The Youth Council
                            continues to receive numerous honors for its work including proclamations and awards from
                            U.S. Congressional Representatives Tom DeLay (Majority Leader -TX), Gregory Meeks (NY)
                            and Henry Howard (GA); NYS Senate Minority Leader Malcolm A. Smith; NYC Council member
                            Leroy Comrie; the NYS Assembly; NY City Council; Atlanta Mayor Shirley Franklin; Dekalb
                            County, GA CEO Vernon Jones; Philadelphia Mayor and Hartford Mayor Eddie Perez.</li>
                        <li>1978 – 2001—Founded Youth Enterprises and Associates, Inc., a private, non-profit Juvenile
                            Delinquency Prevention agency located in Jamaica, Queens. The organization later went on to
                            develop and partner with the Camp Cool J Foundation. The organization received numerous awards
                            and proclamations from a host of elected officials for their work with youth including Mayors Koch, Dinkins and Giuliani.</li>
                        <li>1984 – 1989—Worked as a business consultant for Russell Simmons, former Uptown Records CEO
                            Andre Harrell and Cold Chillin’ Records CEO Tyrone Williams, helping them launch their many
                            ventures.</li>
                        <li>1987—Worked as a consultant to secure the historic Warner Brothers/Cold Chillin’
                            Distribution deal, one of the most successful Hip-Hop Labels in History.</li>
                        <li>1991—Co-discovered two-time Grammy Award winning artist R. Kelly signing the artist to a joint
                            venture deal with Jive Records.</li>
                        <li>1991—Worked as the Executive Director for LL Cool J’s Camp Cool J Foundation and as his Spiritual
                            Advisor.</li>
                        <li>1995-1997—Became LL’s Personal Manager and Business partner successfully guiding his career to
                            a host of achievements and awards including: a 2nd Grammy Award; Partnership and endorsement
                            deal with FUBU apparel; NBC/UPN TV show “In the House”; Publishing deal with St. Martin’s Press
                            for the bestseller “I make my own Rules”; Label deal with Warner Records for the Rock the Bells
                            recording company; an endorsement deal with Coke (1st Hip-Hop celebrity to do so); Endorsement
                            deal with Major League Baseball.</li>
                        <li>1995—Worked as a Consultant to F.U.B.U and helped launch what later became the most successful
                            Minority apparel company in the world ($80,000 - $100 million in gross sales in 1 year).</li>
                        <li>1995—Worked as a Consultant to Quincy Jones on the NBC and UPN-TV show “In the House”
                            starring Debbie Allen and LL Cool J.</li>
                        <li>1996—Worked as an Entertainment Consultant to help President Clinton launch his AmeriCorps
                            program.</li>
                        <li>1997—Worked as a Consultant to Michael Jordan on the “Space Jams” movie.</li>
                        <li>1998—Managed Universal recording artists the Lost Boys.</li>
                        <li>1998—Founder, Chairman & CEO of P.O.G. Enterprises launching Film, Recording, Publishing,
                            Management, Marketing & Media, and Natural Herbs divisions.</li>
                        <li>1999—Author of the book “Power of the Prophets: Preparation for Armageddon (1914-2004)”.</li>
                        <li>2000—Released the “Game Over” anti-drug documentary, which lead to the Miramax/Dimension
                            Film “Paid in Full” starring Mekhi Phifer, Wood Harris and Cam’Ron.</li>
                        <li>2001- Present—Founder and Chairman of the National Hip-Hop Summit Youth Council, Inc.
                            <%= link_to '(www.hhsyc.org)', 'http://www.hhsyc.org/' %>.</li>
                        <li>2005 — Released the award winning “King of Kings” anti-Drug documentary and Soundtrack<!-- 
                            (kingofkingsdvd.com) -->.</li>
                        <li>2005 — Helped organize over 200,000 youths for the Millions More March. One week before the
                            event the Hip-Hop Summit Youth Council was selected as the “Model Program” for the Country by
                            the Millions More Movement Executive Committee.</li>
                        <li>2006 — Partnered with 2 United Nations Intergovernmental Agencies, CISRI-ISP and the World
                            Sports Alliance, to combat Poverty, build youth centers and develop programs that address the
                            Millennium Development Goals.</li>
                        <li>2007 — Partnered with the United Nations Millennium Campaign to solicit the support of 43.7
                            million for their 2007 “STAND UP & SPEAK OUT AGAINST POVERTY” initiative to break the 2006
                            Guinness World Record of 23.5 million.</li>
                        <!-- <h6>For more information, go to: www.hsan.org (under YOUTH COUNCIL) or www.kingofkingsdvd.com</h6> -->





                    </ul>
                </div>
            </div>
        </div>
        <!-- /.row -->

        <hr>

app/views/static_pages/company_structure.html.erb
 <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">HHSYC
                    <small>founded in 2001</small>
                </h1>
                <ol class="breadcrumb">
                    <li><%=link_to 'Home', welcome_path %>
                    </li>  &middot;  
                    <%= link_to "back to About Us", aboutus_path, class: "active" %>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <!-- Sidebar Column -->
                <%= render 'shared/sidebar_column' %>
            <!-- Content Column -->
            <div class="col-md-9">
            	<div class="stylestatic centeritems">
	             	<h3> Company Structure </h3>
	             	<ul class="list-group">
	             		<h5 class="list-group-item">BOARD OF DIRECTORS</h5>
	             	<li class="list-group-item">CHARLES FISHER, Founder &nbsp; &nbsp <%= link_to "(bio)", cf_bio_path %></li>
	             	<li class="list-group-item">Pearl Jones, Chairman</li>
                    <li class="list-group-item">Albert Benjamin</li>
                    <li class="list-group-item">Vanessa Edwards-El</li> 
                    <li class="list-group-item">Steven M. Graham</li>
                    <li class="list-group-item">Det. Victor Logan</li>
                    <li class="list-group-item">Tyrone "Fly Ty" Williams</li>  
              </ul>
              	<ul >
	             		<h5 class="list-group-item">ADVISORY BOARD</h5>  
		             	<li class="list-group-item">"The Shark" Daymond John  &nbsp; &nbsp <%= link_to "(bio)", 'http://daymondjohn.com/about', target: 'blank'%></li>
		             	<li class="list-group-item">Denise Adams</li>
    	                <li class="list-group-item">Marva Allen</li>
    	                <li class="list-group-item">Marilyn Artis</li>
    	                <li class="list-group-item">Dr. Marc Johnson</li>
    	                <li class="list-group-item">Quincy Jones</li>
    	                <li class="list-group-item">Dawn Kelly </li>
    	                <li class="list-group-item">Jose Nino</li>
    	                <li class="list-group-item">Russell Simmons</li>
    	                <li class="list-group-item">Leah Wilcox, NBA</li>
              </ul>
              <ul class="list-group">
	             		<h5 class="list-group-item">STAFF</h5>
		             	<li class="list-group-item">RANDY FISHER, Executive Director &nbsp; &nbsp <%= link_to "(bio)", rf_bio_path %></li>
		             	<li class="list-group-item">Jermaine LaMont, Co-Program Director </li>
    	                <li class="list-group-item">Latifah Johnson, Co-Program Director </li>
    	                <li class="list-group-item">Michelle M. Garcia, Director, Latin Division </li>
              </ul>
	              
			        </div>	
            </div>
        </div>
        <!-- /.row -->

        <hr>

app/views/static_pages/eteam.html.erb
 <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">HHSYC - E-Team
                    <!-- <small>Subheading</small> -->
                </h1>
                <ol class="breadcrumb">
                    <li><%=link_to 'Home', welcome_path %>
                    </li>  &middot;  
                    <%= link_to "back to About Us", aboutus_path, class: "active" %>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <!-- Sidebar Column -->
                <%= render 'shared/sidebar_column' %>
            <!-- Content Column -->
            <div class="col-md-9">
             	<!-- <h2>Section Heading</h2> -->
              
                <div id="3columns" class="list-group-item" style="
    -moz-column-count: 3;   -moz-column-gap: 20px;      -webkit-column-count: 3;   -webkit-column-gap: 20px;   column-count: 3;   column-gap: 20px"></div>
              
            </div>
        </div>
        <!-- /.row -->

        <hr>

app/views/static_pages/joinhhsyc.html.erb
 <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">HHSYC
                    <small>founded in 2001</small>
                </h1>
                <ol class="breadcrumb">
                    <li><%=link_to 'Home', welcome_path %>
                    </li>  
                    <li> 
                    <%= link_to "back to About Us", aboutus_path, class: "active" %>
                    </li>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <!-- Sidebar Column -->
                <%= render 'shared/sidebar_column' %>
            <!-- Content Column -->
            <div class="col-md-9">
            	<div class="stylestatic">
	             	<h3 class="stylestatic">Join HHSYC Now!</h3>
                    <ol class="list-group">
                        <li class="list-group-item"><br>
                            1.  Download an application here <a href="#" >Membership Application</a><br><br>
                        </li>
                        <li class="list-group-item">
                            2.  Complete, sign, date and submit your application via:
                            <ol><br>
                                <li class="list-group-item">
                                    e-mail to: <a href="mailto:info@hhsyc.org?Subject=Application%20to%20start%20a%20chapter" target="_top">info@hhsyc.org</a>
                                </li>
                                <li class="list-group-item">
                                    Fax: 212-353-5083
                                </li>
                                <li class="list-group-item">
                                    US Postal Service<br>
                                    Hip-Hop Summit Youth Council, Inc.<br>
                                    P.O. Box 300925<br>
                                    Jamaica, NY 11430<br>
                                </li>
                            </ol><br>
                        </li>
                        <li class="list-group-item">After your application is received and approved we will notify you via email or phone to give you your Membership Registration Number so you can pay the annual $25 Membership Fee required by all General Members.  You can then send your Money Order to our P.O. Box.</li>
                    </ul>
	              
			    </div>	
            </div>
        </div>
        <!-- /.row -->

        <hr>

app/views/static_pages/mission.html.erb
 <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">HHSYC
                    <small>founded 2001</small>
                </h1>
                <ol class="breadcrumb">
                    <li><%=link_to 'Home', welcome_path %>
                    </li>  &middot;  
                    <%= link_to "back to About Us", aboutus_path, class: "active" %>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <!-- Sidebar Column -->
                <%= render 'shared/sidebar_column' %>
            <!-- Content Column -->
            <div class="col-md-9">
              <div class="stylestatic">
             	 <h3 >Mission Statement</h3>
                <p>
            			The Mission of the Hip-Hop Summit Youth Council (“HHSYC”) is to work as an advocacy group to protect the rights, interest and future of our youths and young adults while addressing a host of issues that confront them daily.  By partnering with schools, the entertainment industry, private and government agencies we have created a unique network that provides the resources to help young people fulfill their social and academic goals.  Through the use of Hip-Hop we have bridged the communication gap between our youths and adults and have earned the trust and respect of both.     
        				</p>
        				<p>
  		            As the Multi-Billion dollar Hip-Hop Culture grows stronger, so does the "Raptivism Movement." It represents the New Social Message behind the Hip-Hop culture.  As we grow as a company Parents, Artists, Executives, Politicians, Clergy, Businessmen and Community Leaders continue to support our work to use Hip-Hop as a tool for enlightenment and social change.  Throughout the years we have created many programs that prepare our participants for the obstacles they will face and the leadership roles they will soon encounter.
        				</p>
        				<p>
  		            To improve the quality of life in our schools and communities we must create an environment that fosters respect, trust and cooperation.  As parents we must take responsibility for the failures and anti-social behavior of our youths and young adults because "It Takes an Entire Village to Raise a Child."  Through our program we will visit schools, youth centers, prisons and housing projects delivering a positive message while offering prizes, awards, grants, scholarships and other incentives that will improve the safety, academic and social development of our youths and young adults.
  		        	</p>
  		        	<h3>Our purpose is to:</h3>
  		        	<ul class="mission_ul">
  		        		<li class="mission_list">Improve the image and unity within the Hip-Hop community, as well as the grades, character and leadership skills of our members.</li>
  		        		<li class="mission_list">Work as an advocacy group with artists, actors, authors, professional athletes, elected officials, clergy and community leaders to address social, political, educational and economic issues that confront our youth each day.</li>
  		        		<li class="mission_list">Monitor the airplay of adult-rated music that is marketed to minors and contain offensive lyrics, negative images, substance abuse, violence and the degradation of women.</li>
  		        		<li class="mission_list">Mediate disputes within the Hip-Hop industry at schools and in the community before they escalate to crime and violence.</li>
  		        		<li class="mission_list">Coordinate workshops with artists to educate them on their social responsibilities to their company, family and community.</li>
  		        		<li class="mission_list">Coordinate workshops to educate the media, community residents, elected officials, clergy, teachers, and businesses on the history of the Hip-Hop culture.</li>
  		        		<li class="mission_list">Produce PSAs with artists that address the social concerns of our youth.</li>
  		        		<li class="mission_list">Provide scholarships, awards and other incentives to students, artists, celebrities, executives, elected officials, community leaders and individuals that are incarcerated.</li>
  		        		<li class="mission_list">Use Hip-Hop as a vehicle to establish an open line of communication which will help improve relations between parents, teachers, elected officials, the clergy, law enforcement agencies and our youth.</li>
  		        		<li class="mission_list">Establish ongoing dialogue between our youth in the U.S. and their peers abroad that will help reduce war, poverty and violence.</li>
  		        		<li class="mission_list">Establish Divisions or Branch Chapters that will help our members acquire the leadership skills, contacts and resources needed to improve the quality of their life as well as conditions in their school and community.</li>
  		        		<li class="mission_list">To register 10 million new voters by the end of 2016.</li>
  		        		<li class="mission_list">To promote the United Nations Millennium Development Goals and the International Decade for a Culture of Peace and Non-violence for the Children of the World.</li>
  		        		<li class="mission_list">Support our men and women who are enrolled in the military and/or deployed in war zones.</li>
  		        	</ul>
              </div>
            </div>
        </div>
        <!-- /.row -->

        <hr>

app/views/static_pages/red.html.erb
 <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">HHSYC - Reality Education Division
                    <!-- <small>founded in 2001</small> -->
                </h1>
                <ol class="breadcrumb">
                    <li><%=link_to 'Home', welcome_path %>
                    </li>  &middot;  
                    <%= link_to "back to About Us", aboutus_path, class: "active" %>
                    </li>  &middot;  
                    <%= link_to "Advisors & Parents (M.A.P)", map_path, class: "active" %>
                    </li>  &middot;  
                    <%= link_to "Camp Celebrity  Division", ccd_path, class: "active" %>
                    </li>  &middot;  
                    <%= link_to "Reality Education Division", red_path, class: "active" %>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <!-- Sidebar Column -->
                <%= render 'shared/sidebar_column' %>
            <!-- Content Column -->
            <div class="col-md-9">
            	<div class="stylestatic">
	             	<!-- <h3>MISSION STATEMENT</h3> -->
	                <p>
		          			The multi-billion dollar Hip-Hop industry is the greatest international cultural phenomenon ever created.  It transcends all racial, ethnic, religious and cultural backgrounds and is the way of life for our youth and young adults.  With all the negativity surrounding Hip-Hop many are unaware that Love; Respect; Peace and Unity are the forgotten characteristics that gave birth to its four basic pillars which include: DJ’ing; MC’ing; Breakdancing; and Graffiti.  Collectively, they are the Body & Soul of the culture.        
	      					</p>
                  <p>
                    America is the greatest country on earth, but is built on a culture that glorifies sex, drugs, guns and violence.  Each has contributed to the decay of our youth and young adults.  To address some of the life threatening problems they are confronted with daily we will launch our Hip-Hop Reality Education project and tour.  With Hip-Hop now being taught in schools and universities throughout the country we will use it as an educational tool to teach participants about Drugs, Guns, Gang Violence, HIV/AIDS, Character Education, Politics, and Economics.  This new innovative concept appeals to the intelligence and sophistication of our youth as opposed to the obsolete “Fear Tactics” used by the “Scared Straight” programs of the 70’s.  That methodology of intimidation is not as effective today because our youth are desensitized from television, film, music, Internet and videogame violence.  Through this project they will better understand how to separate the Realities of the street from the art of Entertainment to improve the quality of their life.
                   </p>
                   <p>
                   	Celebrities, Professional Athletes, Politicians, Executives, Clergy, Law Enforcement Officers, Community Leaders and Ex-offenders will work together to reinforce the goals of the project and provide prizes and incentives to participants.
                   </p>
                   <p>
                   	Through this Project, the Kings of Kings anti-drug documentary and Soundtrack, we will “Flip the Script” and start a new trend that uses Hip-Hop to encourage our participants to graduate from school; improve their character obtain meaningful employment; pursue their Entrepreneurial goals; fulfill their civic duty and avoid the criminal justice system.
                   </p>
			        </div>	
            </div>
        </div>
        <!-- /.row -->

        <hr>