config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  resources :blogs
  resources :announcements

      
  
  get 'adminfisher', to: 'admins#index'

  get 'aboutus', to: 'static_pages#aboutus'
  get 'mission', to: 'static_pages#mission'
  get 'company_history', to: 'static_pages#company_history'
  get 'company_structure', to: 'static_pages#company_structure'
  get 'cf_bio', to: 'static_pages#cf_bio'
  get 'rf_bio', to: 'static_pages#rf_bio'
  get 'hysyc_divisions', to: 'static_pages#hhsyc_divisions'
  get 'startchapter', to: 'static_pages#startchapter'
  get 'joinhhsyc', to: 'static_pages#joinhhsyc'
  get 'ccd', to: 'static_pages#ccd'
  get 'red', to: 'static_pages#red'
  
  get 'projects', to: 'static_pages#projects'
  get 'ebobc', to: 'static_pages#ebobc'
  get 'juneteenth', to: 'static_pages#juneteenth'
  get 'mdg', to: 'static_pages#mdg'
  get 'eteam', to: 'static_pages#eteam'

  get 'announcement/show/:id', to: 'announcements#publicshow', as: 'announcements/show'
  get 'publicannindex', to: 'announcements#publicannindex', as: 'announcementlist'
  # get 'index/announcements/:id', to: 'announcements#publicannindex'
  get 'blog/show/:id', to: 'blogs#blogpubshow', as: 'blogs/show'
  get 'publicblogindex', to: 'blogs#publicblogindex', as: 'bloglist'
  
  
  get 'welcome', to: 'welcome#index'
  


  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
	belongs_to :admin
	mount_uploader :image, ImageUploader
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show, :publicannindex]
  before_action :set_announcement, only: [:show, :edit, :update, :destroy, :publicshow]

  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.all.order('created_at DESC')
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
   @announcements = Announcement.all

  end

  def publicshow
    @announcements = Announcement.all
  end

  def publicannindex
    @announcements = Announcement.all.order('created_at DESC').paginate(page: params[:page], per_page: 2)

  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end


    # if @announcement.save
    #   redirect_to @announcement
    # else
    #   render :new
    # end
  end


  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: 'Announcement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params.require(:announcement).permit(:ann_title, :ann_body, :image).merge(admin: current_admin)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_ann_partial.html.erb
	<div >
     <%= image_tag @announcement.image_url(:medium).to_s %>    
  </div>

	<h3 >
		<%= @announcement.ann_title %>
	</h3>
	<p >
		Submitted <%= time_ago_in_words(@announcement.created_at) %> ago.
	</p>


	<p >
		<%= simple_format(@announcement.ann_body) %>
	</p>

app/views/announcements/_form.html.erb
<%= form_for(@announcement) do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% @announcement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.file_field :image, placeholder: "Upload a photo here (or leave blank to upload an image later" %>
    <%= f.hidden_field :image_cache %>
    <%= f.text_field :ann_title, placeholder: "Enter your announcement or event title here" %>
    <%= f.text_area :ann_body, placeholder: "Enter your announcement or event details here", size: "50x20" %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<% if admin_signed_in? %>

<p id="notice"><%= notice %></p>

 <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">HHSYC - Administrators View
                    <!-- <small>founded in 2001</small> -->
                </h1>
                <ol class="breadcrumb">
                    <li><%=link_to 'Admin Home Page', adminfisher_path %>
                    </li>  
                     <ul>
                          <li class="go-right">
                             <%= link_to "Logout", destroy_admin_session_path, class: "active", method: :delete %>
                          </li>
                     </ul>  
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <!-- Sidebar Column -->
                <%= render 'shared/sidebar_admin' %>
            <!-- Content Column -->
            <div class="col-md-9">
                <div class="stylestatic">
                    <h3>Editing Announcement</h3>
                        <%= render 'form' %>
                        <%= link_to 'View', @announcement %> |
        				<%= link_to 'Back', announcements_path %>
                </div>  
            </div>
        </div>
        <!-- /.row -->

        <hr class="featurette-divider">
            <% else %>

            <%= get '/401', :to => redirect('/401.html') %>

            <% end %>
    </div>

app/views/announcements/index.html.erb
 <!-- Page Content -->
    <div class="container">
      <p id="notice"><%= notice %></p>
        <!-- Page Heading/Breadcrumbs -->
        <% if admin_signed_in? %>
        <%= render 'shared/admin_whitebar' %>
        <% else %>
        <%= render 'shared/public_whitebar' %>
        <% end %>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <!-- Sidebar Column -->
              <% if admin_signed_in? %>
                <%= render 'shared/sidebar_admin' %>
                <% else %>
                <%= render 'shared/sidebar_public' %>
              <% end %>
            <!-- Content Column -->
            <div class="col-md-9">
              <div class="stylestatic">
                <h3>Announcements Listing</h3>
                <table>
                  <thead>
                    <tr>
                      <th colspan="3"></th>
                    </tr>
                  </thead>

                    <tbody>
                      <% @announcements.each do |announcement| %>
                        <tr>
                          <td><%= link_to announcement.ann_title, announcement %></td>
                          <td><%= announcement.created_at.strftime("%b %d, %Y - %I:%M %p") %></td>
                          <td><%= link_to 'View', announcement %></td>
                          <% if admin_signed_in? %>
                          <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
                          <td><%= link_to 'Delete', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td><% end %>
                        </tr>
                      <% end %>
                    </tbody>
                </table>
                <% if admin_signed_in? %>
                <%= link_to 'New Event Post', new_announcement_path %>
                <% end %>
              </div>  
            </div>
        </div>
        <!-- /.row -->

        <hr class="featurette-divider">

app/views/announcements/new.html.erb
<p id="notice"><%= notice %></p>

 <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">HHSYC - Administrators View
                    <!-- <small>founded in 2001</small> -->
                </h1>
                <ol class="breadcrumb">
                    <li><%=link_to 'Admin Home Page', adminfisher_path %>
                    </li>  
                    
                    <ul>
                          <li class="go-right">
                              <%= link_to "Logout", destroy_admin_session_path, class: "active", method: :delete %>
                            </li>
                     </ul>
                    </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <!-- Sidebar Column -->
                <%= render 'shared/sidebar_admin' %>
            <!-- Content Column -->
            <div class="col-md-9">
              <div class="stylestatic">
                <h3>New Announcements</h3>
                  <% if admin_signed_in? %>

										<%= render 'form' %>

										<%= link_to 'Back', announcements_path %>

										<% else %>

										<%=link_to "You are not authorized to post new announcements", url: '401.html' %>

									<% end %>
              </div>  
            </div>
        </div>
        <!-- /.row -->

        <hr class="featurette-divider">

app/views/announcements/publicannindex.html.erb
<!-- Page Content -->
    <div class="container">
        <p id="notice"><%= notice %></p>

        <!-- Page Heading/Breadcrumbs -->
        
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>

                    <h2 class="intro-text text-center">HHSYC
                        <strong>Announcement and Events</strong>
                    </h2>

                    <hr>
                    <div class="row">
            <div class="col-lg-12">
                <!-- <h1 class="page-header">HHSYC - Administrators View -->
                    <!-- <small>founded in 2001</small> -->
                <!-- </h1> -->
                <ol class="breadcrumb">
                    <li><%=link_to 'Back', :back %>
                </ol>
            </div>
        </div>
                </div>
                <% @announcements.each do |announcement| %>
                <div class="col-lg-12 text-center">
                    
                    <%= image_tag(announcement.image.url(:medium), class: "img-responsive img-border center-block img-rounded img-full") %>
                    <h2><%= announcement.ann_title %>
                        <br>
                        <small><%= announcement.created_at.strftime("%b %d, %Y - %I:%M %p") %></small>
                    </h2>
                    <p class="h2para"><%= truncate(announcement.ann_body, length: 300, omission: "... (continued)") %></p>
                    <%= link_to "View Details", announcement_path(announcement), :class => "btn btn-default" %><% end %>
                    <hr>
                </div>
                
                <div class="col-lg-12 text-center">
                    <ul class="pager">
                        <li class="previous"><a href="#">&larr; Newer</a>
                        </li>
                        <li class="next"><a href="#">Older &rarr;</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- /.row -->

        <hr class="featurette-divider">

    <nav>
      <ul class="paginate-block pagination-sm">
        <li><%= will_paginate @announcements, renderer: BootstrapPagination::Rails, next_label: "Older", previous_label: "Newer", page_links: false %>
        </li>
      </ul>
    </nav>

app/views/announcements/publicshow.html.erb
<!-- Page Content -->
    <div class="container">
        <p id="notice"><%= notice %></p>

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <!-- <h1 class="page-header">HHSYC - Administrators View -->
                    <!-- <small>founded in 2001</small> -->
                <!-- </h1> -->
                <ol class="breadcrumb">
                    <li><%=link_to 'Back', :back %>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <!-- Sidebar Column -->
                <%= render 'shared/sidebar_public' %>
            <!-- Content Column -->
            <div class="col-md-9">
                <div class="stylestatic">
                    <div >
                        <%= render 'ann_partial' %>
                    </div>
                </div>  
            </div>
        </div>
        <!-- /.row -->

        <hr class="featurette-divider">
   

app/views/announcements/show.html.erb
<!-- Page Content -->
    <div class="container">
        <p id="notice"><%= notice %></p>
        <% if admin_signed_in? %>
        <!-- Page Heading/Breadcrumbs -->
        <%= render 'shared/admin_whitebar' %>
        <% else %>
        <%= render 'shared/public_whitebar' %>
        <% end %>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <!-- Sidebar Column -->
            <% if admin_signed_in? %>
                <%= render 'shared/sidebar_admin' %>
                <% else %>
                <%= render 'shared/sidebar_public' %>
            <% end %>
            <!-- Content Column -->
            <div class="col-md-9">
                <div class="stylestatic">
                    <div>
                        <div >
                           <%= image_tag @announcement.image_url(:medium).to_s %>    
                        </div>
                        <h3 >
                            <%= @announcement.ann_title %>
                        </h3>
                            <p >
                            Submitted <%= time_ago_in_words(@announcement.created_at) %> ago.
                            <% if admin_signed_in? %>
                            | &nbsp; <%= link_to 'Back', announcements_path %>&nbsp;
                            
                        |   &nbsp; <%= link_to 'Edit', edit_announcement_path(@announcement) %>&nbsp;
                        |    &nbsp; <%= link_to 'Delete', announcement_path(@announcement),method: :delete, data: { confirm: 'Are you sure?'} %>
                        <% else %>
                        | &nbsp; <%= link_to 'Back', :back %>&nbsp;
                            <% end %>
                            </p>
                            <p >
                                <%= simple_format(@announcement.ann_body) %>
                            </p>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->

        <hr class="featurette-divider">
   