config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  resources :blogs
  resources :announcements

      
  
  get 'adminfisher', to: 'admins#index'

  get 'aboutus', to: 'static_pages#aboutus'
  get 'mission', to: 'static_pages#mission'
  get 'company_history', to: 'static_pages#company_history'
  get 'company_structure', to: 'static_pages#company_structure'
  get 'cf_bio', to: 'static_pages#cf_bio'
  get 'rf_bio', to: 'static_pages#rf_bio'
  get 'hysyc_divisions', to: 'static_pages#hhsyc_divisions'
  get 'startchapter', to: 'static_pages#startchapter'
  get 'joinhhsyc', to: 'static_pages#joinhhsyc'
  get 'ccd', to: 'static_pages#ccd'
  get 'red', to: 'static_pages#red'
  
  get 'projects', to: 'static_pages#projects'
  get 'ebobc', to: 'static_pages#ebobc'
  get 'juneteenth', to: 'static_pages#juneteenth'
  get 'mdg', to: 'static_pages#mdg'
  get 'eteam', to: 'static_pages#eteam'

  get 'announcement/show/:id', to: 'announcements#publicshow', as: 'announcements/show'
  get 'publicannindex', to: 'announcements#publicannindex', as: 'announcementlist'
  # get 'index/announcements/:id', to: 'announcements#publicannindex'
  get 'blog/show/:id', to: 'blogs#blogpubshow', as: 'blogs/show'
  get 'publicblogindex', to: 'blogs#publicblogindex', as: 'bloglist'
  
  
  get 'welcome', to: 'welcome#index'
  


  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/admins/index.html.erb
 <% if admin_signed_in? %>
 <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">HHSYC - Administrators View
                    <!-- <small>founded in 2001</small> -->
                </h1>
                <ol class="breadcrumb">
                    <li><%=link_to 'Admin Home Page', welcome_path %>
                    </li>  
                     <ul>
             			<li class="go-right">
             			    <%= link_to "Logout", destroy_admin_session_path, class: "active", method: :delete %>
            			</li>
                     </ul>
                    
                  
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <!-- Sidebar Column -->
                <%= render 'shared/sidebar_admin' %>
            <!-- Content Column -->
            <div class="col-md-9">
            	<div class="stylestatic">
	             	<h3>Welcome to the Admin Dashboard</h3>
                    <h4>
                        From this gateway,  you may access the menu to the left for announcements, blogs, or images
                    </h4><br><br>
			     </div>	
            </div>
        </div>
        <!-- /.row -->

        <hr>
   <% else %>
        	<li><%= link_to 'Admin Log In', admin_session_path %></li>
<% end %>