config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  resources :blogs
  resources :announcements

      
  
  get 'adminfisher', to: 'admins#index'

  get 'aboutus', to: 'static_pages#aboutus'
  get 'mission', to: 'static_pages#mission'
  get 'company_history', to: 'static_pages#company_history'
  get 'company_structure', to: 'static_pages#company_structure'
  get 'cf_bio', to: 'static_pages#cf_bio'
  get 'rf_bio', to: 'static_pages#rf_bio'
  get 'hysyc_divisions', to: 'static_pages#hhsyc_divisions'
  get 'startchapter', to: 'static_pages#startchapter'
  get 'joinhhsyc', to: 'static_pages#joinhhsyc'
  get 'ccd', to: 'static_pages#ccd'
  get 'red', to: 'static_pages#red'
  
  get 'projects', to: 'static_pages#projects'
  get 'ebobc', to: 'static_pages#ebobc'
  get 'juneteenth', to: 'static_pages#juneteenth'
  get 'mdg', to: 'static_pages#mdg'
  get 'eteam', to: 'static_pages#eteam'

  get 'announcement/show/:id', to: 'announcements#publicshow', as: 'announcements/show'
  get 'publicannindex', to: 'announcements#publicannindex', as: 'announcementlist'
  # get 'index/announcements/:id', to: 'announcements#publicannindex'
  get 'blog/show/:id', to: 'blogs#blogpubshow', as: 'blogs/show'
  get 'publicblogindex', to: 'blogs#publicblogindex', as: 'bloglist'
  
  
  get 'welcome', to: 'welcome#index'
  


  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/shared/_admin_whitebar.html.erb
<div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">HHSYC - Administrators View
                    <!-- <small>founded in 2001</small> -->
                </h1>
                <ol class="breadcrumb">
                    <li><%=link_to 'Admin Home Page', adminfisher_path %>
                    </li>  
                    <ul>
                          <li class="go-right">
                              <%= link_to "Logout", destroy_admin_session_path, class: "active", method: :delete %>
                           </li>
                     </ul>
                </ol>
            </div>
        </div>

app/views/shared/_modal.html.erb
<!-- Button trigger modal -->
<!-- <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button> -->

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>

app/views/shared/_page_heading.html.erb
<!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">About the HHSYC
                    <small>Subheading</small>
                </h1>
                <ol class="breadcrumb">
                    <li><%=link_to 'Home', welcome_path %>
                    </li>
                    <li class="active">Sidebar Page</li>
                </ol>
            </div>
        </div>

app/views/shared/_public_whitebar.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header text-center">HHSYC.Org
        <small>Hip-Hop Against Gun & Gang Violence</small>
    </h1>
    <ol class="breadcrumb">
        <li><%= link_to 'Back', :back %>
        <li><%= link_to 'Dashboard', announcements_path%></li>
    </ol>
  </div>
</div>

app/views/shared/_sidebar_admin.html.erb
<!-- Sidebar Column -->
            <div class="col-md-3">
                <div class="list-group">
                    <%= link_to "New Event or Announcement", new_announcement_path, class: "list-group-item" %>
                    <%= link_to "View All Announcements", announcements_path, class: "list-group-item" %>
                    <%= link_to "New Blog Post", new_blog_path, class: "list-group-item" %>
                    <%= link_to "View All Blog Posts", blogs_path, class: "list-group-item" %>
                    <%= link_to "New Photo for Gallery", announcements_path, class: "list-group-item" %>
                </div>
            </div>

app/views/shared/_sidebar_column.html.erb
<!-- Sidebar Column -->
            <div class="col-md-3">
                <div class="list-group">
                    <%= link_to "Mission Statement", mission_path, class: "list-group-item" %>
                    <%= link_to "Company History", company_history_path, class: "list-group-item" %>
                    <%= link_to "Company Structure", company_structure_path, class: "list-group-item" %>                    
                    <%= link_to "Start a HHSYC Chapter", startchapter_path, class: "list-group-item" %>
                    
                    <%= link_to "Join HHSYC Now", joinhhsyc_path, class: "list-group-item" %>
                </div>
            </div>

app/views/shared/_sidebar_projects.html.erb
<!-- Sidebar Column -->
            <div class="col-md-3">
                <div class="list-group">
                    <%= link_to "EBOBC Project", ebobc_path, class: "list-group-item" %>
                    <%= link_to "Juneteenth", juneteenth_path, class: "list-group-item" %>
                    <%= link_to "Millennium Development Goals", mdg_path, class: "list-group-item" %>
                    <%= link_to "E Team Members", eteam_path, class: "list-group-item" %>
                                      
                    
                    
                    
                </div>
            </div>

app/views/shared/_sidebar_public.html.erb
<!-- Sidebar Column -->
            <div class="col-md-3">
                <div class="list-group">
                    <%= link_to "View All Announcements", announcementlist_path, class: "list-group-item" %>
                    <%= link_to "View All Blog Posts", bloglist_path, class: "list-group-item" %>
                    <%= link_to "View Photo Gallery", announcements_path, class: "list-group-item" %>
                </div>
            </div>